//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application size.
        /// </summary>
        public static string appSize {
            get {
                return ResourceManager.GetString("appSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string btnSettingsSave {
            get {
                return ResourceManager.GetString("btnSettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team information.
        /// </summary>
        public static string btnTeamInformation {
            get {
                return ResourceManager.GetString("btnTeamInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string croatian {
            get {
                return ResourceManager.GetString("croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string fullScreen {
            get {
                return ResourceManager.GetString("fullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player information.
        /// </summary>
        public static string playerInformationTitle {
            get {
                return ResourceManager.GetString("playerInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settingsTitle {
            get {
                return ResourceManager.GetString("settingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string small {
            get {
                return ResourceManager.GetString("small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team information.
        /// </summary>
        public static string teamInformationTitle {
            get {
                return ResourceManager.GetString("teamInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament type.
        /// </summary>
        public static string tournamentType {
            get {
                return ResourceManager.GetString("tournamentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain: .
        /// </summary>
        public static string txtCaptain {
            get {
                return ResourceManager.GetString("txtCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa code: .
        /// </summary>
        public static string txtFifaCode {
            get {
                return ResourceManager.GetString("txtFifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals received: .
        /// </summary>
        public static string txtGoalsReceived {
            get {
                return ResourceManager.GetString("txtGoalsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals scored: .
        /// </summary>
        public static string txtGoalsScored {
            get {
                return ResourceManager.GetString("txtGoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawn matches: .
        /// </summary>
        public static string txtMatchesDraw {
            get {
                return ResourceManager.GetString("txtMatchesDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches lost: .
        /// </summary>
        public static string txtMatchesLost {
            get {
                return ResourceManager.GetString("txtMatchesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches played: .
        /// </summary>
        public static string txtMatchesPlayed {
            get {
                return ResourceManager.GetString("txtMatchesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches won: .
        /// </summary>
        public static string txtMatchesWon {
            get {
                return ResourceManager.GetString("txtMatchesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string txtPlayerName {
            get {
                return ResourceManager.GetString("txtPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: .
        /// </summary>
        public static string txtPosition {
            get {
                return ResourceManager.GetString("txtPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt number: .
        /// </summary>
        public static string txtShirtNumber {
            get {
                return ResourceManager.GetString("txtShirtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string txtTeamName {
            get {
                return ResourceManager.GetString("txtTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards: .
        /// </summary>
        public static string txtYellowCards {
            get {
                return ResourceManager.GetString("txtYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World cup.
        /// </summary>
        public static string worldCupTitle {
            get {
                return ResourceManager.GetString("worldCupTitle", resourceCulture);
            }
        }
    }
}
